---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Download Xdebug.
  get_url:
    url: "http://xdebug.org/files/xdebug-{{ php_xdebug_version }}.tgz"
    dest: "{{ workspace }}/xdebug-{{ php_xdebug_version }}.tgz"

# TODO: In 2.0, we can set the 'src' to the URL from the get_url task above and
# cut out one extra task :)
- name: Untar Xdebug.
  unarchive:
    src: "{{ workspace }}/xdebug-{{ php_xdebug_version }}.tgz"
    dest: "{{ workspace }}"
    copy: no
  register: php_xdebug_untar

- name: Build Xdebug.
  shell: >
    {{ item }}
    chdir={{ workspace }}/xdebug-{{ php_xdebug_version }}
    creates={{ workspace }}/xdebug-{{ php_xdebug_version }}/modules/xdebug.so
  with_items:
    - phpize
    - ./configure
    - make
  notify: restart webserver

- name: Ensure Xdebug module path exists.
  file:
    path: "{{ php_xdebug_module_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Ensure old version was removed.
  shell: >
    rm {{ php_xdebug_module_path }}/xdebug.so
    removes={{ php_xdebug_module_path }}/xdebug.so
  when: php_xdebug_untar.changed

- name: Move Xdebug module into place.
  shell: >
    cp {{ workspace }}/xdebug-{{ php_xdebug_version }}/modules/xdebug.so {{ php_xdebug_module_path }}/xdebug.so
    creates={{ php_xdebug_module_path }}/xdebug.so
  notify: restart webserver

- include: configure.yml
